//
// Created by Sam on 10/13/2020.
//

#ifndef LINKED_LIST_SAMPLE_LINKEDLISTEXCEPTION_H
#define LINKED_LIST_SAMPLE_LINKEDLISTEXCEPTION_H

class LinkedListException{

};

#endif //LINKED_LIST_SAMPLE_LINKEDLISTEXCEPTION_H
